# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup', '0017_auto_20160421_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20, verbose_name='token')),
                ('user_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='setup.UserApplication')),
            ],
        ),
    ]
