# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 15:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=30, verbose_name='middle name')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('applied_before', models.BooleanField(verbose_name='applied before')),
                ('year_applied', models.CharField(max_length=4, null=True, verbose_name='year applied')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
