# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='gender',
            field=models.CharField(choices=[('', 'Select'), ('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='gender'),
            preserve_default=False,
        ),
    ]
