# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_personalinformation_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='gender',
            field=models.CharField(choices=[('', 'Select'), ('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='middle_name',
            field=models.CharField(max_length=30, verbose_name='middle name'),
        ),
    ]
