# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160331_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='applied_before',
            field=models.NullBooleanField(verbose_name='applied before'),
        ),
    ]
