# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160331_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='applied_before',
            field=models.BooleanField(default=False, verbose_name='applied before'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='gender'),
        ),
    ]
