# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160331_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='applied_before',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='applied before'),
        ),
    ]
