# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(max_length=30, verbose_name='middle name')),
                ('date_of_birth', models.DateField(null=True, verbose_name='date of birth')),
                ('applied_before', models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='applied before')),
                ('year_applied', models.CharField(max_length=4, null=True, verbose_name='year applied')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='gender')),
            ],
        ),
    ]
