# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staff'},
        ),
        migrations.RemoveField(
            model_name='form',
            name='application',
        ),
        migrations.AlterField(
            model_name='application',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='application open?'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Application'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Form'),
        ),
    ]
