# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_auto_20160402_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='setup.Organization'),
            preserve_default=False,
        ),
    ]
