# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 19:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setup', '0003_application_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date')),
                ('submit_date', models.DateTimeField(verbose_name='submit date')),
                ('form_filled_count', models.PositiveSmallIntegerField(default=0, verbose_name='number of forms filled')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
