# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 21:51
from __future__ import unicode_literals

from django.db import migrations
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_auto_20160402_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='slug',
            field=utils.AutoSlugField(db_index=False, default=1, populate_from='form.name'),
            preserve_default=False,
        ),
    ]
