# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0011_auto_20160402_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_slug', models.CharField(max_length=50, verbose_name='form slug')),
            ],
        ),
        migrations.RemoveField(
            model_name='userapplication',
            name='form_filled_count',
        ),
        migrations.AddField(
            model_name='savedform',
            name='user_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.UserApplication'),
        ),
    ]
