# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 11:08
from __future__ import unicode_literals

from django.db import migrations
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0013_auto_20160407_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='slug',
            field=utils.AutoSlugField(db_index=False, populate_from='name'),
        ),
    ]
