# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0014_auto_20160415_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='year'),
        ),
        migrations.AddField(
            model_name='organization',
            name='short_name',
            field=models.CharField(default='ashesi', max_length=20, verbose_name='organization short name'),
            preserve_default=False,
        ),
    ]
