# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0015_auto_20160415_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
