# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 12:00
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.sites.models import Site

def insert_site_data(apps, schema_editor):
    current_site = Site.objects.get_current()
    pk = current_site.pk
    if pk == 1:
        current_site.name = 'Apply Central Dev'
        current_site.domain = 'localhost:8000'
    elif pk == 2:
        current_site.name == 'Apply Central Demo'
        current_site.domain = 'demo.applycentral.net'
    elif pk == 3:
        current_site.name == 'Apply Central'
        current_site.domain == 'applycentral.net'
    current_site.save()

class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0017_auto_20160421_1716'),
    ]

    operations = [
        migrations.RunPython(insert_site_data)
    ]
