# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0017_auto_20160421_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='amount',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='amount'),
        ),
        migrations.AddField(
            model_name='application',
            name='receive_payment',
            field=models.BooleanField(default=False, verbose_name='receive payment?'),
        ),
    ]
