# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0018_auto_20160422_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='amount',
            new_name='fee',
        ),
        migrations.RemoveField(
            model_name='application',
            name='receive_payment',
        ),
        migrations.AddField(
            model_name='application',
            name='receive_fee',
            field=models.BooleanField(default=False, verbose_name='receive fee?'),
        ),
    ]
