# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0019_auto_20160422_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='fee',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='fee'),
        ),
    ]
