# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0020_auto_20160422_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapplication',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='is complete'),
        ),
    ]
