# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0021_userapplication_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
