# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0023_auto_20160424_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
