# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 16:48
from __future__ import unicode_literals

import ashesiundergraduate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashesiundergraduate', '0003_scholarships'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalinformation',
            options={'verbose_name_plural': 'Personal Information'},
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='photo',
            field=models.ImageField(default=1, height_field='photo_height', upload_to=ashesiundergraduate.models.get_upload_path, width_field='photo_width'),
            preserve_default=False,
        ),
    ]
