# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 23:09
from __future__ import unicode_literals

import ashesiundergraduate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashesiundergraduate', '0005_auto_20160405_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='photo',
            field=models.ImageField(height_field='photo_height', help_text='File name must be in the format firstname_lastname.', upload_to=ashesiundergraduate.models.get_upload_path, width_field='photo_width'),
        ),
    ]
