# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 08:32
from __future__ import unicode_literals

import ashesiundergraduate.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setup', '0012_auto_20160404_1117'),
        ('ashesiundergraduate', '0006_auto_20160405_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_of_citizenship', models.CharField(max_length=50, verbose_name='country of citizenship')),
                ('user_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='setup.UserApplication')),
            ],
        ),
        migrations.CreateModel(
            name='PassportDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=20, verbose_name='passport number')),
                ('expiry_date', models.DateField(verbose_name='expiry date')),
                ('user_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.UserApplication')),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('town', models.CharField(max_length=50, verbose_name='town')),
                ('state', models.CharField(max_length=50, verbose_name='state')),
                ('country', models.CharField(max_length=50, verbose_name='country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='photo',
            field=models.ImageField(height_field='photo_height', help_text='File name must be in the format - Firstname_Lastname.jpg', upload_to=ashesiundergraduate.models.get_upload_path, width_field='photo_width'),
        ),
    ]
