# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashesiundergraduate', '0007_auto_20160407_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='photo',
            field=models.ImageField(height_field='photo_height', help_text='File name must be in the format - Firstname_Lastname.jpg', upload_to='photos/%Y-%m-%d/', width_field='photo_width'),
        ),
    ]
