# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashesiundergraduate', '0008_auto_20160407_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='photo_height',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='photo_width',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='year_applied',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='year applied'),
        ),
    ]
