# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashesiundergraduate', '0012_passportdetails_user_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residence',
            old_name='user',
            new_name='user_application',
        ),
    ]
