# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashesiundergraduate', '0014_auto_20160408_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='living_with',
            field=models.CharField(choices=[('', 'Select'), ('PG', 'I live with my parent(s)/guardian(s)'), ('SELF', 'I live by myself'), ('ORPH', 'I live in an orphanage')], default='', max_length=4, verbose_name='who do you live with?'),
            preserve_default=False,
        ),
    ]
