# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 14:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ashesiundergraduate', '0016_orphanage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphanage',
            name='contact_person_phone_number',
            field=models.CharField(help_text='Enter phone number in the format +233xxxxxxxxx', max_length=15, verbose_name='contact person phone number'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2016, 4, 12, 14, 40, 34, 67485, tzinfo=utc), verbose_name='date of birth'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='gender'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='photo_height',
            field=models.CharField(default=2, max_length=5, verbose_name='photo height'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='photo_width',
            field=models.CharField(default=2, max_length=5, verbose_name='photo width'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='year_applied',
            field=models.CharField(default=1994, max_length=4, verbose_name='year applied'),
            preserve_default=False,
        ),
    ]
