# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0013_auto_20160407_1131'),
        ('ashesiundergraduate', '0018_auto_20160412_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('have_passport', models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='have passport')),
                ('user_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.UserApplication')),
            ],
        ),
        migrations.RemoveField(
            model_name='passportdetails',
            name='user_application',
        ),
        migrations.AddField(
            model_name='passportdetails',
            name='passport_check',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='ashesiundergraduate.PassportCheck'),
            preserve_default=False,
        ),
    ]
