# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashesiundergraduate', '0020_auto_20160414_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desiredmajor',
            old_name='major',
            new_name='desired_major',
        ),
    ]
