# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashesiundergraduate', '0022_auto_20160421_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='course name'),
        ),
    ]
