# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ashesiundergraduate', '0023_auto_20160423_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passportcheck',
            name='user_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='setup.UserApplication'),
        ),
    ]
