# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 23:16
from __future__ import unicode_literals

import ashesiundergraduate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashesiundergraduate', '0025_auto_20160428_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='photo',
            field=models.ImageField(height_field='photo_height', upload_to=ashesiundergraduate.models.get_upload_path, width_field='photo_width'),
        ),
    ]
